FROM python:3.11-slim-bullseye

COPY . /app

WORKDIR /app
RUN apt-get update && apt-get install -y redis-server &&  apt-get clean
RUN pip install -e . && mkdir -p /app/data
ENV ASYNC_ALLOW=True
CMD ["sh", "-c", "cd /app/data && redis-server --daemonize yes && python -m openad_service_utils.api.server"] 
# sh -c redis-server --daemonize yes && python -m openad_service_utils.api.server